# Generated by Django 5.2.3 on 2025-07-02 18:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code_iso_2', models.CharField(help_text='Code ISO 3166-1 alpha-2 (2 caractères)', max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('code_iso_3', models.CharField(help_text='Code ISO 3166-1 alpha-3 (3 caractères)', max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)])),
                ('indicatif_tel', models.CharField(help_text='Indicatif téléphonique international', max_length=10)),
                ('devise', models.CharField(default='XOF', max_length=10)),
                ('fuseau_horaire', models.CharField(default='UTC', max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'db_table': 'pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude en degrés décimaux (-90 à +90)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude en degrés décimaux (-180 à +180)', max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.IntegerField(default=0, help_text='Altitude en mètres au-dessus du niveau de la mer')),
                ('population', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='villes', to='geography.pays')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'db_table': 'villes',
                'ordering': ['pays__nom', 'nom'],
                'unique_together': {('pays', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='communes', to='geography.ville')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'db_table': 'communes',
                'ordering': ['ville__nom', 'nom'],
                'unique_together': {('ville', 'nom')},
            },
        ),
    ]
