# Generated by Django 5.2.3 on 2025-07-02 18:56

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('niveau', models.IntegerField(default=0, help_text='Niveau hiérarchique (0-100)')),
                ('permissions', models.JSONField(default=dict, help_text='Permissions spécifiques en format JSON')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'roles',
                'ordering': ['-niveau', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('email_verifie', models.BooleanField(default=False)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('mfa_active', models.BooleanField(default=False)),
                ('mfa_secret', models.CharField(blank=True, max_length=100)),
                ('mfa_type', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('TOTP', 'TOTP'), ('APP', 'Application')], default='SMS', max_length=20)),
                ('cles_de_recuperation', models.JSONField(default=list, help_text='Clés de récupération MFA')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('ip_derniere_connexion', models.GenericIPAddressField(blank=True, null=True)),
                ('tentatives_connexion', models.IntegerField(default=0)),
                ('bloque_jusqu', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('bloque', models.BooleanField(default=False)),
                ('raison_blocage', models.TextField(blank=True)),
                ('derniere_maj_mdp', models.DateTimeField(default=django.utils.timezone.now)),
                ('force_changement_mdp', models.BooleanField(default=False)),
                ('accepte_conditions', models.BooleanField(default=False)),
                ('version_conditions', models.CharField(blank=True, max_length=10)),
                ('accepte_marketing', models.BooleanField(default=False)),
                ('langue_preferee', models.CharField(default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('type_code', models.CharField(choices=[('email_verification', 'Vérification email'), ('phone_verification', 'Vérification téléphone'), ('password_reset', 'Réinitialisation mot de passe'), ('login_verification', 'Vérification connexion')], max_length=30)),
                ('email_cible', models.EmailField(blank=True, help_text="Email à vérifier si différent de l'actuel", max_length=254)),
                ('telephone_cible', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text="Téléphone à vérifier si différent de l'actuel", max_length=128, region=None)),
                ('tentatives_utilisation', models.IntegerField(default=0)),
                ('max_tentatives', models.IntegerField(default=3)),
                ('expire_at', models.DateTimeField()),
                ('utilise_at', models.DateTimeField(blank=True, null=True)),
                ('adresse_ip_creation', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code OTP',
                'verbose_name_plural': 'Codes OTP',
                'db_table': 'codes_otp',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('adresse', models.TextField(blank=True)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('coordonnees_gps', models.JSONField(blank=True, help_text='Coordonnées GPS {lat, lng}', null=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('societe', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('notification_email', models.BooleanField(default=True)),
                ('notification_sms', models.BooleanField(default=True)),
                ('notification_push', models.BooleanField(default=True)),
                ('visibilite_profil', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé'), ('amis', 'Amis seulement')], default='public', max_length=20)),
                ('derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.pays')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.ville')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'db_table': 'profils',
            },
        ),
        migrations.CreateModel(
            name='SessionUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_session', models.CharField(max_length=255, unique=True)),
                ('adresse_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField()),
                ('derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'db_table': 'sessions_utilisateur',
            },
        ),
        migrations.CreateModel(
            name='UtilisateurRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attribution', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_attribues', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.role')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attribution de rôle',
                'verbose_name_plural': 'Attributions de rôles',
                'db_table': 'utilisateurs_roles',
                'unique_together': {('utilisateur', 'role')},
            },
        ),
    ]
