# Generated by Django 5.2.3 on 2025-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(default='user_default', error_messages={'unique': 'Un utilisateur avec ce nom existe déjà.'}, help_text='Requis. 150 caractères maximum. Lettres, chiffres et @/./+/-/_ seulement.', max_length=150, unique=True, verbose_name="nom d'utilisateur"),
        ),
    ]
